branches:
  - master
dryRun: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  -
    - "@semantic-release/github"
    - assets:
      - path: "packages/*.nupkg"
        label: Packages
