branches:
  - master
dryRun: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  -
    - "@semantic-release/github"
    - assets:
      - path: TestApp/bin/Release/netcoreapp3.1
        label: TestApp.exe

